# Change these first
owner: cafeeurope # Your GitHub organization or username, where this repository lives
repo: status.cafe-europe.info # The name of this repository

sites:
  - name: Infohalle (prod)
    url: http://portal.infohalle.com/
  - name: Infohalle (stage)
    url: https://stage-portal.infohalle.com/
  - name: typo3
    url: https://nachrichtenaustausch.ch/typo3/
  - name: punkt4
    url: http://punkt4.info/
  - name: swisstrade
    url: http://swisstrade.com/
  - name: cafe europe
    url: http://cafe-europe.info/
  - name: ce email
    url: https://host.cafe-europe.info/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.cafe-europe.info
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/cafeeurope/status.cafe-europe.info/master/assets/celogo.png
  name: Status
  introTitle: "uptime monitor and status page"
  introMessage: ""
  navbar:
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
